trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: S3

- name: S3_BUCKET
  value: s3-htmx-static-files-378377821393-us-east-1-an

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'

- script: |
    python --version
    pip --version
  displayName: Verify Python

- script: |
    pip install -r requirements.txt
  displayName: Install Dependencies

- script: |
    python3 build.py
  displayName: Build Site

- script: |
    aws --version

    echo "logs"
    echo "=== Identity ==="
    aws sts get-caller-identity

    echo "=== Bucket ==="
    echo $(S3_BUCKET)

    echo "=== Dist Directory ==="
    pwd
    ls -la
    ls -la dist

    echo "=== List Objects ==="
    aws s3api list-objects-v2 \
      --bucket $(S3_BUCKET) \
      --max-items 5
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
  displayName: Validate AWS Access

- script: |
    aws s3 sync \
      dist/ \
      s3://$(S3_BUCKET) \
      --delete \
      --exact-timestamps \
      --debug
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
  displayName: Deploy S3